#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --exclude compute[100,102,103,104,105,106,108,109,110,111,127]
#SBATCH --time 00:3:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --output d2q9-bgk.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

#! Run the executable
srun --mpi=pmi2 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
make check128
#srun --mpi=pmi2 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
#make check256
#srun --mpi=pmi2 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
#make check1024

#srun --mpi=pmi2 -n 2 -c 1 advixe-cl -v -collect survey -project-dir=./IntelStuff -data-limit=0 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
#srun --mpi=pmi2 -n 2 -c 1 advixe-cl -v -collect tripcounts --flop -project-dir=./IntelStuff -data-limit=0 ./d2q9-bgk input_256x256.params obstacles_256x256.dat


#srun -mpi=pmi2 -n 29 ./d2q9-bgk input etc etc